### DISCUSSION TITLE
Localization  for All Localizable Data

### DISCUSSION THREAD

**Discussion by kozmotronik** [chipzoller/hugo-clarity#455] [General]
Hi there!
I pleasently use this nice theme. I'm trying to build a multilingual blog site, however having trouble with localization of some global variables like `introDescription` and `disclaimerText`.  
My goal is to localize all description-like text to three different languages; Turkish, Spanish and English. I have already created their respective localization files under the `i18n` directory. I am trying to localize the `introDescription` and the `disclaimerText` in their respective localization file, but these informations seem to derived only from the `params.toml` file. Because when I comment them out, these informations dissappear from the sidebar despite their definition in the localization files.  

This is how I define them in the localization, for example en.toml:
**en.toml**
```toml
[introDescription]
  other = "Student, teacher, continual incremental improvement. Enthusiastic and passionate of electronics and programming, especially on embedded development."

[disclaimerText]
  other = "This site is for informational purposes. The practitioner applies the information presented here at his own responsibility and risk. The practitioner is entirely responsible for any damage, loss of life or property, material or physical losses that may occur due to negligence, carelessness, lack of knowledge on the subject or incorrect application during the application of this information, so the site and its authors cannot be held responsible."
```
I've also tried changing the variable names as `[intro_description]` and `[disclaimer_text]` but no avail. How can I do so that those variables derive from the localization files? Thank you.
